<h3><b>Introduction to Data Analytics - Exercise set 5 - data processing and management</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.<br /><br />
<span style="font-weight: bold;">Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does!</span><br />

<span style="font-weight: bold;">Remember: your Jupyter notebook's clarity (how easy it is to read and understand) also affects your scoring!</span><br /><br />
<span style="font-weight: bold;">Remember also: 
<span style="font-weight: bold;">If you use generative AI in any part of any exercise, 
MENTION IT CLEARLY! </span><br />
<span style="font-weight: bold;">(code comments are enough, also mention the prompts used).</span><br /><br />
See also the materials discussing the usage of AI in this course!</span><br /><br />


You can return all of these exercises in a single Jupyter Notebook, if you wish.

<p style="color: red;"><b>NOTE: The JSON/XML –files in Moodle in these exercises have been randomly generated. In other words, the data doesn't make any sense!</b></p>

In [16]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import json

<h4><b>1. </b>Download <b>"simple.json"</b> in Moodle, and load it in pandas.</b> </h4>
<p>
The DataFrame should look like this:
</p>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex51.png" width="1000"/>

In [4]:
# Loading simple.json into a dataframe.
df = pd.read_json("simple.json")
df.head(5)

,id,brand,model,year,owned_by,acquired,price
0,1,Chrysler,Voyager,2001,Wolff-Trantow,28/12/2016,11565
1,2,Volkswagen,Jetta,1995,"Schuppe, Pfeffer and Klein",20/4/2016,52431
2,3,Porsche,Cayenne,2005,Mante Group,11/6/2020,75552
3,4,Porsche,928,1994,Wisozk Group,17/6/2019,30331
4,5,Mercedes-Benz,SL-Class,2007,Schiller-Littel,20/7/2018,62385

<h4><b>2.</b> Download <b>"simple.xml"</b> in Moodle, and load it in pandas</h4>
<p>
<span style="color: red"><b>(Note:</b> if using pandas.read_xml(), use also the xpath-parameter!)</span><br /><br >The Series should look something like this:
</p>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex52.png" />

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex52cars.jpg" width="600" />

In [6]:
# Reading an XML file into a Pandas dataframe.
df = pd.read_xml("simple.xml", xpath="/*")
df.head(1)

   id       brand   model  year                    owned_by    acquired  price
0   1  Oldsmobile  Aurora  2003  Herzog, Rodriguez and Howe  21/10/2016  32571

<h4><b>3. Load this API-data into a pandas DataFrame:</b></h4>
<p><a href="https://edu.frostbit.fi/api/events/en">https://edu.frostbit.fi/api/events/en</a></p>

<p>
Remember to use json_normalize to help you out with the categories and address information.<br /><b>Have address information in their own columns, and categories as separate rows.</b><br />The DataFrame should look something like this (note that the data changes daily, and exact values will vary):


</p>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex53.png"/>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex53events.jpg" width="600" />

In [25]:
# code here
# https://edu.frostbit.fi/api/events/en

# define the URL.
url = "https://edu.frostbit.fi/api/events/en"
page = requests.get(url)

# create a 'soup' object of the raw web-page.
soup = BeautifulSoup(page.content, 'html.parser')

soup

[{"name": "Join a virtual journey \u2013 experience culture at the library", "date": "22.5.2025", "categories": ["cultural events", "exhibitions", "guidance", "lepp\u00e4vaara", "libraries", "literature", "museums", "older people"], "address": {"street_address": "Lepp\u00e4vaarankatu 9", "postal_code": "02600"}}, {"name": "Playground Loru\u2019s programme 10.3.-14.3.2025", "date": "29.4.2025", "categories": ["cultural events", "fine arts", "music"], "address": {"street_address": "T\u00f6\u00f6l\u00f6nlahdenkatu 4", "postal_code": "00100"}}, {"name": "Playground Loru\u2019s programme 10.3.-14.3.2025", "date": "30.4.2025", "categories": ["cultural events", "fine arts", "music"], "address": {"street_address": "T\u00f6\u00f6l\u00f6nlahdenkatu 4", "postal_code": "00100"}}, {"name": "Loop the Break 2025", "date": "16.5.2025", "categories": ["dance (performing arts)", "music", "participation", "street dance"], "address": {"street_address": "T\u00f6\u00f6l\u00f6nkatu 51 a-b", "postal_code": "00250"}}, {"name": "ENTER ry IT tutoring for seniors", "date": "30.10.2025", "categories": [], "address": {"street_address": "Lepp\u00e4vaarankatu 9", "postal_code": "02600"}}, {"name": "ENTER ry IT tutoring for seniors", "date": "27.11.2025", "categories": ["guidance", "lepp\u00e4vaara", "libraries", "older people"], "address": {"street_address": "Lepp\u00e4vaarankatu 9", "postal_code": "02600"}}, {"name": "HPO: Janowski &amp; Due\u00f1as", "date": "25.4.2025", "categories": ["concerts", "cultural events", "music"], "address": {"street_address": "Mannerheimintie 13a", "postal_code": "00100"}}, {"name": "nternational Museum Day: The Observatory", "date": "18.5.2025", "categories": ["astronomy", "cultural events", "science"], "address": {"street_address": "Kopernikuksentie 1", "postal_code": "00130"}}, {"name": "Crip Cin\u00e9 Film Festival 2025", "date": "8.5.2025", "categories": ["cultural events", "film festivals", "films", "french language"], "address": {"street_address": "Yrj\u00f6nkatu 36", "postal_code": "00100"}}, {"name": "HPO \u2013 Encounters Club ", "date": "9.5.2025", "categories": ["concerts", "cultural events", "music"], "address": {"street_address": "Mannerheimintie 13a", "postal_code": "00100"}}, {"name": "HPO: Iisakkila, Danik &amp; Nieminen", "date": "1.5.2025", "categories": ["concerts", "cultural events", "music"], "address": {"street_address": "Mannerheimintie 13a", "postal_code": "00100"}}]

<h4><b>4. Use web scraping (e.g. BeautifulSoup), and use it to get the following info from the Rovaniemi Wikipedia –page</b></h4>
<p><b>Wiki-page:</b> <a href="https://en.wikipedia.org/wiki/Rovaniemi">https://en.wikipedia.org/wiki/Rovaniemi</a></p>

<b>Tasks:</b>
<ul>
    <li>Get the coordinates of Rovaniemi (upper right corner)</li>
    <li>Get the nickname of Rovaniemi (under coat of arms)</li>
</ul>

<b>Advanced extra tasks:</b>
<ul>
    <li><b>Get the total population</b></li>
    <ul>
        <li><b>Note:</b> this is a good example why webscraping can be tedious, since you'll have to traverse the HTML-tree to get what you want. This might be helpful:<br />
<a href="https://realpython.com/beautiful-soup-web-scraper-python/">https://realpython.com/beautiful-soup-web-scraper-python/</a></li>
    </ul>
    
</ul>

<ul>
    <li><b>Get the total area</b></li>
    <ul>
        <li>Convert this number into a float decimal (i.e. remove commas and the unit and call float() –in Python!)</li>
    </ul>
    
</ul>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex54rovaniemi.jpg" width="600" />

In [ ]:
# code here

<h4><b>5. Use web scraping, and create a DataFrame of this table: </b></h4>
<p> <a href="https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature">https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature</a></p>

<ul>
    <li>Change the name of the value column to "avg_temp" as well (pandas column rename)</li>
</ul>
<ul>
    <li><b>Small extra task: </b>clean up the column so that only the 
numeric °C-value is present (no other characters)
</li>
</ul>

<b>Advanced extra task:</b>
<ul>
    <li><b>Scrape these two tables as well</b></li>
    <ul>
        <li><a href="https://en.wikipedia.org/wiki/List_of_countries_by_employment_rate">https://en.wikipedia.org/wiki/List_of_countries_by_employment_rate</a></li>
        <li><a href="https://en.wikipedia.org/wiki/List_of_countries_by_unemployment_rate">https://en.wikipedia.org/wiki/List_of_countries_by_unemployment_rate</a></li>
    </ul>
    <br />
    <ul>
        <li><b>Combine the tables into a single DataFrame so that you get only the data of year 2020 or newer, and have the columns <span style="color: darkorange">"Country", "EmploymentRate"</span> and <span style="color: darkorange">"UnemploymentRate"</span>. You can also create additional columns <span style="color: red">"EmploymentRate15_24"</span>and <span style="color: red">"EmploymentRate25_70"</span> if you scrape the OECD-table as well! </b>

</li>
    </ul>
</ul>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex55stocks.jpg" width="450" />

<h4><b>6. Simple merging:</b> Download <u><b>coffee_sales.csv</b></u> and <b><u>temperatures_fixed.csv</u></b> from Moodle.<b></h4>
<p>Use merging to combine these files into one DataFrame, containing the coffee sales data and the corresponding temperature –data. (merge(), see materials for examples)</p>

<span style="color: red;"><b>Use left join, and coffee sales as the first DataFrame!</b></span>

In [ ]:
# code here

<b>Extra task: </b> Do the same but with <b>temperatures_unfixed.csv</b> instead. Remember <b>groupby()</b> before attempting merging! 

<b>Also, you might want to remove some of the columns before grouping data => <span style="color: red;">Summary + Hour</span>. </b>

<span><i>You can also try to merge the DataFrames so that the Summary –of the weather is also added. For this, you probably need to figure out first how to determine the "average" Summary for each day (extra challenge!).</i></span>

In [ ]:
# extra task code here, if done

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex56coffee.jpg" width="450" />


<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<ul>
<li><b>1. Download the "complex.json" –file from Moodle.</b> Note that this data is fairly complex (i.e. heavily nested). Use json_normalize and other needed methods to convert this data into a workable DataFrame.</li>
</ul>

In [3]:
# code for the advanced extra task

<ul>
<li><b>2. Load the "simple.json" –file without pandas, and try to get the average price with plain Python. <b>(DON'T USE AI HERE)</b></li>
</ul>

In [1]:
# code for the advanced extra task

<ul>
<li><b>3. Download the "complex.xml" file from Moodle, and create a DataFrame out of it.</b></li>
<ul>
    <li><b>Note:</b> using pandas.read_xml() would otherwise work, but it ignores the "ownership" –field. You'll have to find another way to get this data into your DataFrame as well!</li>
</ul>
</ul>

In [ ]:
# code for the advanced extra task, you can also create a separate notebook for this 
# (might be a better idea, since a new dataset always adds quite much new code)

<ul>
    <li><b>4. Try out Selenium on a site that cannot be scraped with traditional methods. You can use this tutorial as the starting point:</b></li>
    <ul>
        <li><a href="https://www.toptal.com/python/web-scraping-with-python">https://www.toptal.com/python/web-scraping-with-python</a></li>
    </ul>
</ul>

In [ ]:
# code for the advanced extra task, you can also create a separate notebook for this 
# (might be a better idea, since a new dataset always adds quite much new code)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex5charts.jpg" width="600" />

<b>5. Extra challenging advanced task: <span style="color: red;">integrating data sources</span></b>

<ul>
<li><b>Integrate two or more datasets into one matching dataset (pandas DataFrame), but use any datasets you can find in Kaggle.com instead of the previous coffee sales + temperature -datasets</b></li>
<br />
<ul>
<li>Find two or more datasets (Kaggle.com etc.) that have something in common and can be used for merging. </li>
</ul>

<br />
<ul>
<li><b>Typical common columns:</b></li>
<ul>
<li>Coordinates (lat/lng etc.)</li>
<li>Years, months</li>
<li>reference ids (e.g. product id -> product data)</li>
</ul>
</ul>

<br />
<ul>
<li><b>You can use pandas.merge() in order to combine DataFrames</b></li>
<ul>
<li>When combining DataFrames, make sure that the merge doesn’t mess up your data</li>
<li><b>Note:</b> merge can often create way too many extra rows depending on the merging parameters</li>

</ul>
</ul>

<br />
<ul>
<li><b>This exercise can provide even large amounts of points, depending on difficulty. Aspects that affect grading:</b></li>
<ul>
<li>Amount of datasets</li>
<li>Difficulty of the datasets</li>
<li>Using different data formats all at once (XML, JSON, CSV etc.)</li>
<li>Other techniques used to add data: web scraping, data APIs etc.</li>
</ul>
</ul>


</ul>

In [ ]:
# this exercise is probably better to do in a separate Jupyter notebook